FROM alpine:3.22.2

RUN apk update && apk add --no-cache \
    python3 \
    py3-pip \
    git \
    bash \
    nano \
    vim


RUN ln -sf python3 /usr/bin/python

WORKDIR /app

RUN git clone https://github.com/levimaciell/Gemini-Api-Test.git

RUN python3 -m venv bandit-env && \
    . bandit-env/bin/activate && \
    pip install --upgrade pip && \
    pip install bandit && \
    pip install semgrep && \
    pip install google-genai

RUN mkdir results

RUN chmod +x Gemini-Api-Test/exec_sast.sh

CMD ["/bin/bash", "-c", "source bandit-env/bin/activate && exec bash"]